### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by leasunhy** [peterbjorgensen/DeepDFT#2]
This is a very excellent work!

A few questions about the datasets:

* Are the datasets for training the model available publicly? Where can I download/access the QM9 dataset that is augmented with the electron density information (`qm9vasp` perhaps)?
* If the datasets are not publicly available, could you provide some instructions on running Gaussian/VASP on QM9 to obtain the required data?
* What is the rough compute/time cost for data collection?

Thanks in advance!

**Comment by peterbjorgensen** [comment]
Thanks for your interest. We are currently working on a new version of the model and the plan is to publish all the datasets with it.
I might be able to share the QM9 VASP dataset earlier. I can post a link within a few days.

**Comment by leasunhy** [comment]
> Thanks for your interest. We are currently working on a new version of the model and the plan is to publish all the datasets with it. I might be able to share the QM9 VASP dataset earlier. I can post a link within a few days.

Thanks! I'm looking forward to it 😄

**Comment by peterbjorgensen** [comment]
Here is a temporary link to the QM9 VASP dataset https://figshare.com/s/6e1a0cb63653d1112035
It will eventually be turned into a proper dataset entry with a doi. Until then, you can use this link

**Comment by leasunhy** [comment]
👍 Well received. Many thanks for your prompt reply!

**Comment by ismsgithub** [comment]
This is a very creative work! But I can't use the link https://data.dtu.dk/articles/dataset/QM9_Charge_Densities_and_Energies_Calculated_with_VASP/16794500 for downloading. It shows 403 after I click the "download" button.

**Comment by peterbjorgensen** [comment]
> This is a very creative work! But I can't use the link https://data.dtu.dk/articles/dataset/QM9_Charge_Densities_and_Energies_Calculated_with_VASP/16794500 for downloading. It shows 403 after I click the "download" button.

Thanks for letting me know. I have contacted the data responsible team and hopefully they will get back to us soon.
