### ISSUE TITLE
datasplits.json for the pretrained models

### ISSUE THREAD

**Issue by KonstantinUshenin** [peterbjorgensen/DeepDFT#5]
I am very impressed by this excellent model and technical solution. 

Could you provide the `datasplits.json` files for the pre-trained models?

**Comment by peterbjorgensen** [comment]
For QM9:
https://data.dtu.dk/articles/dataset/QM9_Charge_Densities_and_Energies_Calculated_with_VASP/16794500?file=31085455

For EC:
https://data.dtu.dk/articles/dataset/Ethylene_Carbonate_Molecular_Dynamics/16691825?file=31013233
